#!/usr/bin/env python3
import re

with open('i18n.js', 'r', encoding='utf-8') as f:
    content = f.read()

# All remaining languages
remaining_langs = '''  ,
  
  // 法语
  fr: {
    appName: 'AiFriend',
    appSubtitle: 'Votre compagnon IA',
    send: 'Envoyer',
    cancel: 'Annuler',
    confirm: 'Confirmer',
    close: 'Fermer',
    welcomeMessage: 'Salut ! Je suis AiFriend, choisis un personnage pour commencer ✨',
    greeting: 'Bonjour',
    roleSquare: 'Galerie de personnages',
    selectRole: 'Sélectionner un personnage',
    currentRole: 'Rôle actuel',
    changeRole: 'Changer de rôle',
    categories: {
      female: 'Personnages féminins',
      male: 'Personnages masculins',
      fantasy: 'Personnages fantastiques'
    },
    roles: {
      sister: { name: 'Femme mature', desc: 'Élégante et charmante' },
      loli: { name: 'Douce fille', desc: 'Mignonne et innocente' },
      girlfriend: { name: 'Petite amie', desc: 'Douce et attentionnée' },
      ceo: { name: 'PDG', desc: 'Elite commerciale capable' },
      nurse: { name: 'Infirmière', desc: 'Douce et attentionnée' },
      senior: { name: 'Étudiante senior', desc: 'Intellectuelle et élégante' },
      star: { name: 'Idole', desc: 'Glamour et éblouissante' },
      athlete: { name: 'Sportive', desc: 'Énergique et en bonne santé' },
      teacher: { name: 'Enseignante', desc: 'Patiente et inspirante' },
      artist: { name: 'Artiste', desc: 'Romantique et créative' },
      gamer: { name: 'Gameuse', desc: 'Amusante et énergique' },
      boyfriend: { name: 'Petit ami doux', desc: 'Attentionné et romantique' },
      dominantCeo: { name: 'PDG dominant', desc: 'Puissant et dévoué' },
      schoolmate: { name: 'Ami d\\'enfance', desc: 'Attentionné et familier' },
      werewolf: { name: 'Loup-garou', desc: 'Sauvage et loyal' },
      vampire: { name: 'Vampire', desc: 'Mystérieux et élégant' },
      angel: { name: 'Ange', desc: 'Pur et saint' },
      demon: { name: 'Démon', desc: 'Séduisant et mystérieux' }
    },
    freeTries: 'Messages gratuits',
    remainingTries: '{count} restants',
    noMoreTries: 'Messages gratuits épuisés',
    upgradeMembership: 'Mettre à niveau',
    becomeMember: 'Devenir membre',
    membershipBenefits: 'Avantages membres',
    unlimitedChats: 'Chats illimités',
    allRoles: 'Tous les personnages',
    longTermMemory: 'Mémoire à long terme',
    prioritySupport: 'Support prioritaire',
    buyWithStars: 'Acheter avec Stars',
    monthly: 'Mensuel',
    yearly: 'Annuel',
    lifetime: 'À vie',
    price: {
      monthly: '100 Stars/mois',
      yearly: '1000 Stars/an',
      lifetime: '3000 Stars à vie'
    },
    settings: 'Paramètres',
    language: 'Langue',
    clearHistory: 'Effacer l\\'historique',
    about: 'À propos',
    typingPlaceholder: 'Tapez un message...',
    sending: 'Envoi...',
    errorSending: 'Échec de l\\'envoi',
    networkError: 'Erreur réseau',
    chatHistory: 'Historique des discussions',
    noHistory: 'Pas d\\'historique',
    clearConfirm: 'Effacer tout l\\'historique?',
    cleared: 'Effacé',
    firstTimeTitle: 'Bienvenue sur AiFriend!',
    firstTimeSubtitle: 'Choisissez un personnage pour commencer',
    continueChat: 'Continuer',
    newChat: 'Nouveau chat',
    backToHistory: 'Retour à l\\'historique'
  },
  
  // 德语
  de: {
    appName: 'AiFriend',
    appSubtitle: 'Dein KI-Begleiter',
    send: 'Senden',
    cancel: 'Abbrechen',
    confirm: 'Bestätigen',
    close: 'Schließen',
    welcomeMessage: 'Hallo! Ich bin AiFriend, wähle einen Charakter zum Starten ✨',
    greeting: 'Hallo',
    roleSquare: 'Charakter-Galerie',
    selectRole: 'Charakter wählen',
    currentRole: 'Aktuelle Rolle',
    changeRole: 'Rolle wechseln',
    categories: {
      female: 'Weibliche Charaktere',
      male: 'Männliche Charaktere',
      fantasy: 'Fantasy-Charaktere'
    },
    roles: {
      sister: { name: 'Reife Dame', desc: 'Elegant und charmant' },
      loli: { name: 'Süßes Mädchen', desc: 'Niedlich und unschuldig' },
      girlfriend: { name: 'Freundin', desc: 'Süß und fürsorglich' },
      ceo: { name: 'CEO', desc: 'Fähige Business-Elite' },
      nurse: { name: 'Krankenschwester', desc: 'Sanft und fürsorglich' },
      senior: { name: 'Senior-Studentin', desc: 'Intellektuell und elegant' },
      star: { name: 'Idol', desc: 'Glamourös und atemberaubend' },
      athlete: { name: 'Sportliches Mädchen', desc: 'Energiegeladen und gesund' },
      teacher: { name: 'Lehrerin', desc: 'Geduldig und inspirierend' },
      artist: { name: 'Künstlerin', desc: 'Romantisch und kreativ' },
      gamer: { name: 'Gamer-Girl', desc: 'Lustig und energiegeladen' },
      boyfriend: { name: 'Sanfter Freund', desc: 'Fürsorglich und romantisch' },
      dominantCeo: { name: 'Dominanter CEO', desc: 'Mächtig und hingebungsvoll' },
      schoolmate: { name: 'Jugendfreund', desc: 'Fürsorglich und vertraut' },
      werewolf: { name: 'Werwolf', desc: 'Wild und loyal' },
      vampire: { name: 'Vampir', desc: 'Mysteriös und elegant' },
      angel: { name: 'Engel', desc: 'Rein und heilig' },
      demon: { name: 'Dämon', desc: 'Verführerisch und mysteriös' }
    },
    freeTries: 'Kostenlose Nachrichten',
    remainingTries: '{count} übrig',
    noMoreTries: 'Kostenlose Nachrichten aufgebraucht',
    upgradeMembership: 'Upgrade',
    becomeMember: 'Mitglied werden',
    membershipBenefits: 'Mitgliedervorteile',
    unlimitedChats: 'Unbegrenzte Chats',
    allRoles: 'Alle Charaktere',
    longTermMemory: 'Langzeitgedächtnis',
    prioritySupport: 'Prioritäts-Support',
    buyWithStars: 'Mit Stars kaufen',
    monthly: 'Monatlich',
    yearly: 'Jährlich',
    lifetime: 'Lebenslang',
    price: {
      monthly: '100 Stars/Monat',
      yearly: '1000 Stars/Jahr',
      lifetime: '3000 Stars lebenslang'
    },
    settings: 'Einstellungen',
    language: 'Sprache',
    clearHistory: 'Verlauf löschen',
    about: 'Über',
    typingPlaceholder: 'Nachricht eingeben...',
    sending: 'Senden...',
    errorSending: 'Senden fehlgeschlagen',
    networkError: 'Netzwerkfehler',
    chatHistory: 'Chat-Verlauf',
    noHistory: 'Kein Chat-Verlauf',
    clearConfirm: 'Gesamten Chat-Verlauf löschen?',
    cleared: 'Gelöscht',
    firstTimeTitle: 'Willkommen bei AiFriend!',
    firstTimeSubtitle: 'Wähle einen Charakter zum Starten',
    continueChat: 'Fortsetzen',
    newChat: 'Neuer Chat',
    backToHistory: 'Zurück zum Verlauf'
  },
  
  // 葡萄牙语
  pt: {
    appName: 'AiFriend',
    appSubtitle: 'Seu companheiro de IA',
    send: 'Enviar',
    cancel: 'Cancelar',
    confirm: 'Confirmar',
    close: 'Fechar',
    welcomeMessage: 'Olá! Sou AiFriend, escolha um personagem para começar ✨',
    greeting: 'Olá',
    roleSquare: 'Galeria de personagens',
    selectRole: 'Selecionar personagem',
    currentRole: 'Papel atual',
    changeRole: 'Mudar papel',
    categories: {
      female: 'Personagens femininos',
      male: 'Personagens masculinos',
      fantasy: 'Personagens de fantasia'
    },
    roles: {
      sister: { name: 'Mulher madura', desc: 'Elegante e charmosa' },
      loli: { name: 'Garota doce', desc: 'Fofa e inocente' },
      girlfriend: { name: 'Namorada', desc: 'Doce e carinhosa' },
      ceo: { name: 'CEO', desc: 'Elite empresarial capaz' },
      nurse: { name: 'Enfermeira', desc: 'Gentil e carinhosa' },
      senior: { name: 'Veterana', desc: 'Intelectual e elegante' },
      star: { name: 'Ídolo', desc: 'Glamourosa e deslumbrante' },
      athlete: { name: 'Garota atlética', desc: 'Enérgica e saudável' },
      teacher: { name: 'Professora', desc: 'Paciente e inspiradora' },
      artist: { name: 'Artista', desc: 'Romântica e criativa' },
      gamer: { name: 'Garota gamer', desc: 'Divertida e enérgica' },
      boyfriend: { name: 'Namorado gentil', desc: 'Carinhoso e romântico' },
      dominantCeo: { name: 'CEO dominante', desc: 'Poderoso e devotado' },
      schoolmate: { name: 'Amigo de infância', desc: 'Carinhoso e familiar' },
      werewolf: { name: 'Lobisomem', desc: 'Selvagem e leal' },
      vampire: { name: 'Vampiro', desc: 'Misterioso e elegante' },
      angel: { name: 'Anjo', desc: 'Puro e santo' },
      demon: { name: 'Demônio', desc: 'Sedutor e misterioso' }
    },
    freeTries: 'Mensagens grátis',
    remainingTries: '{count} restantes',
    noMoreTries: 'Mensagens grátis esgotadas',
    upgradeMembership: 'Atualizar',
    becomeMember: 'Tornar-se membro',
    membershipBenefits: 'Benefícios de membro',
    unlimitedChats: 'Chats ilimitados',
    allRoles: 'Todos os personagens',
    longTermMemory: 'Memória de longo prazo',
    prioritySupport: 'Suporte prioritário',
    buyWithStars: 'Comprar com Stars',
    monthly: 'Mensal',
    yearly: 'Anual',
    lifetime: 'Vitalício',
    price: {
      monthly: '100 Stars/mês',
      yearly: '1000 Stars/ano',
      lifetime: '3000 Stars vitalício'
    },
    settings: 'Configurações',
    language: 'Idioma',
    clearHistory: 'Limpar histórico',
    about: 'Sobre',
    typingPlaceholder: 'Digite uma mensagem...',
    sending: 'Enviando...',
    errorSending: 'Falha ao enviar',
    networkError: 'Erro de rede',
    chatHistory: 'Histórico de chat',
    noHistory: 'Sem histórico de chat',
    clearConfirm: 'Limpar todo o histórico de chat?',
    cleared: 'Limpo',
    firstTimeTitle: 'Bem-vindo ao AiFriend!',
    firstTimeSubtitle: 'Escolha um personagem para começar',
    continueChat: 'Continuar',
    newChat: 'Novo chat',
    backToHistory: 'Voltar ao histórico'
  }'''

# Find insertion point
insert_pos = content.find('\n};\n\n// 获取翻译文本')
if insert_pos != -1:
    new_content = content[:insert_pos] + remaining_langs + content[insert_pos:]
    with open('i18n.js', 'w', encoding='utf-8') as f:
        f.write(new_content)
    print("✅ Added French, German, Portuguese")
else:
    print("❌ Could not find insertion point")
